apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: privatebin
  namespace: privatebin
spec:
  interval: 1m
  chart:
    spec:
      chart: privatebin
      sourceRef:
        kind: HelmRepository
        name: privatebin
        namespace: privatebin
      interval: 1m
  test:
    enable: true
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    replicaCount: 2
    name: privatebin

